backend:
  name: git-gateway
  branch: main
publish_mode: editorial_workflow
media_folder: "public/assets/uploads"
public_folder: "/assets/uploads"

collections: 
- name: "hero-banner"
  label: "Hero Banner"
  files:
  - label: "Data"
    name: "Hero-banner"
    file: src/data.json
    format: "json"
    create: true
    slug: "data"
    fields:
        - label: "Hero Banner" #Nom dans le CMS
          name: "hero" #Nom dans data.json
          widget: "object" #Type de donnée
          fields:
            - { label: "Titre", name: "title", widget: "string"}
            - { label: "Sub-Title", name: "paragraph", widget: "string"}
            - { label: "Button", name: "button", widget: "string"}
            - { label: "Image", name: "image", widget: "image"}
- name: "Contact"
  label: "Contact"
  files:
  - label: "Data"
    name: "Contact"
    file: src/data.json
    format: "json"
    create: true
    slug: "data"
    fields:
        - label: "Contact Section" #Nom dans le CMS
          name: "contact" #Nom dans data.json
          widget: "object" #Type de donnée
          fields:
            - { label: "Titre", name: "title", widget: "string"}
            - { label: "Sub-Title", name: "subtitle", widget: "string"}
            - { label: "Input Value", name: "input-value", widget: "string"}
            - { label: "Input Submit Value", name: "submit-value", widget: "string"}
- name: "Service"
  label: "Service"
  files:
  - label: "Data"
    name: "Service"
    file: src/data.json
    format: "json"
    create: true
    slug: "data"
    fields:
        - label: "Services Section" #Nom dans le CMS
          name: "services" #Nom dans data.json
          widget: "object" #Type de donnée
          fields:
            - { label: "Titre", name: "title", widget: "string"}
            - { label: "Sub-Title", name: "subtitle", widget: "string"}
            - label: "Services"
              name: "cart"
              widget: "list"
              fields:
                - { label: "Id", name: "id", widget: "number"}
                - { label: "Source", name: "src", widget: "image"}
                - { label: "Title", name: "title", widget: "string"}
                - { label: "Content", name: "content", widget: "string"}